AWSTemplateFormatVersion: 2010-09-09
Description: >
  Demonstration of looking up plain text stuff in SSM Secure stuff
  only works for slots that have secure item handling eg, database passwords
  https://aws.amazon.com/blogs/mt/using-aws-systems-manager-parameter-store-secure-string-parameters-in-aws-cloudformation-templates/
Parameters:
  AlphaType:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /bonzo/parameter/alpha
  BetaType:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /bonzo/parameter/beta
 
Resources:
  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'aaaaa.aws.donhenton.sample.${AlphaType}'
      Tags:
      - Key: beta
        Value: "{{resolve:ssm:/bonzo/parameter/beta:1}}"
    DeletionPolicy: Delete

Outputs:
  BetaValue:
    Description: 'beta value'
    Value: !Ref BetaType
  GammaValue:
    Description: 'beta value'
    Value: "{{resolve:ssm:/bonzo/parameter/beta:1}}"
    Export:
      Name: !Sub '${AWS::StackName}-BetaValue'